---
title: "Stat 251 Final Project: Disney vs. Lucasfilm"
author: "Aaron Brown, Aly Milne, Andrew Bergeron"
date: "11/15/2023"
output: pdf_document
---

```{r setup, include=FALSE}
library(tinytex)
library(tidyverse)
library(vroom)
library(invgamma)
library(readxl)
```

```{r answer1b}
# Read in data
star_wars_raw <- read.csv("cleaned_SW_ratings.csv")
# view(star_wars_main)

star_wars_clean <- star_wars_raw[!is.na(star_wars_raw$AverageRating), ]
# rownames(star_wars_clean) <- NULL
# view(star_wars_clean)

# Mean avg rating
mean(star_wars_clean$AverageRating)
```

```{r answer1a}
# PRIOR PARAMETERS: We'll use the same prior for both populations

# Prior parameters for mu: 
lambda <- 8
tau2 <- 20
# Prior parameters for sigma2: 
# possible range for reviews is ~1-10, 
# then an approximate standard deviation would be 9/12
# so an approximate variance would be 0.4444
gamma <- 2.01
phi <- 0.666666
#prior expected value of variance: 
phi/(gamma-1)
```

```{r answer1c}
# Plot the prior distributions to make sure they seem reasonable
par(mfrow=c(1,2))
curve(dnorm(x, lambda, sqrt(tau2)), xlim=c(-5, 25), ylab="prior density", main=expression(pi(mu)), xlab=expression(mu))
curve(dinvgamma(x, gamma, phi), xlim=c(0, 3), ylab="prior density", main=expression(pi(sigma^2)), xlab=expression(sigma^2))
```

Disney acquisition was end of 2012, so everything prior to and in the year of 2012 will be LucasFilm and 2013 and after will be Disney:
```{r}
data_before_2013 <- filter(star_wars_clean, startYear < 2013)
view(data_before_2013)

data_2013_and_after <- filter(star_wars_clean, startYear >= 2013)
```

```{r}

mean(data_before_2013$AverageRating)
var(data_before_2013$AverageRating)

mean(data_2013_and_after$AverageRating)
var(data_2013_and_after$AverageRating)

```


```{r}

### LucasFilm:

n <- nrow(data_before_2013)

#############################################
# POSTERIOR DISTRIBUTIONS: use Gibbs Sampling
#############################################
# Starting values:
mu <- mean(data_before_2013$AverageRating)
sigma2 <- var(data_before_2013$AverageRating)

# initializations for the Gibbs Sampling Algorithm
iters <- 10000
mu.save <- rep(0, iters)
mu.save[1] <- mu
sigma2.save <- rep(0, iters)
sigma2.save[1] <- sigma2

#Gibbs Sampling Algorithm
for(t in 2:iters){
  
  # Full conditional of mu (update the value of the parameters)
  lambda.p <- (tau2*sum(data_before_2013$AverageRating) + sigma2*lambda)/(tau2*n + sigma2)
  tau2.p <- sigma2*tau2/(tau2*n + sigma2)
  #sample a new value of mu
  mu <- rnorm(1, lambda.p, sqrt(tau2.p))
  #save the value of mu
  mu.save[t] <- mu
  
  # full conditional of sigma2 (update the value of the parameters)
  gamma.p <- gamma + n/2
  phi.p <- phi + sum((data_before_2013$AverageRating - mu)^2 )/2
  #sample new value of sigma2
  sigma2 <- rinvgamma(1, gamma.p, phi.p)
  #save the value of sigma2
  sigma2.save[t] <- sigma2
  
}

# Trace plots (decide if we need to throw out the first few values):
# par(mfrow=c(1,2))
plot(mu.save, type='l')
plot(sigma2.save, type='l')


#throw out the first few values
burn <- 100
mu.use <- mu.save[-(1:burn)]
sigma2.use <- sigma2.save[-(1:burn)]
plot(mu.use, type='l')
plot(sigma2.use, type='l')

#SUMMARIZE THE POSTERIOR DISTRIBUTION(S)
# posterior distribution of mu 
#plot 
plot(density(mu.use), xlab=expression(mu[L]), ylab="density", main=expression(pi(mu[L]~"|"~data)))
# #add prior
# curve(dnorm(x, lambda, sqrt(tau2)), lty=2, add=T)
#add legend
# legend("topright", c("Posterior"))
mean(mu.use)

muL.use <- mu.use

# posterior distribution of sigma2
par(mfrow=c(1,1))
plot(density(sigma2.use), xlab=expression(sigma[L]^2), main=expression(pi(sigma[L]^2~"|"~data)))
# #add prior
# curve(dinvgamma(x, gamma, phi), add=T, lty=2, xlim=c(0, 1))
#add legend
# legend("topright", c("Posterior"))
mean(sigma2.use)

sigma2L.use <- sigma2.use

```

```{r}

### Disney:

n <- nrow(data_2013_and_after)

#############################################
# POSTERIOR DISTRIBUTIONS: use Gibbs Sampling
#############################################
# Starting values:
mu <- mean(data_2013_and_after$AverageRating)
sigma2 <- var(data_2013_and_after$AverageRating)

# initializations for the Gibbs Sampling Algorithm
iters <- 10000
mu.save <- rep(0, iters)
mu.save[1] <- mu
sigma2.save <- rep(0, iters)
sigma2.save[1] <- sigma2

#Gibbs Sampling Algorithm
for(t in 2:iters){
  
  # Full conditional of mu (update the value of the parameters)
  lambda.p <- (tau2*sum(data_2013_and_after$AverageRating) + sigma2*lambda)/(tau2*n + sigma2)
  tau2.p <- sigma2*tau2/(tau2*n + sigma2)
  #sample a new value of mu
  mu <- rnorm(1, lambda.p, sqrt(tau2.p))
  #save the value of mu
  mu.save[t] <- mu
  
  # full conditional of sigma2 (update the value of the parameters)
  gamma.p <- gamma + n/2
  phi.p <- phi + sum((data_2013_and_after$AverageRating - mu)^2 )/2
  #sample new value of sigma2
  sigma2 <- rinvgamma(1, gamma.p, phi.p)
  #save the value of sigma2
  sigma2.save[t] <- sigma2
  
}

# Trace plots (decide if we need to throw out the first few values):
# par(mfrow=c(1,2))
plot(mu.save, type='l')
plot(sigma2.save, type='l')


#throw out the first few values
burn <- 150
mu.use <- mu.save[-(1:burn)]
sigma2.use <- sigma2.save[-(1:burn)]
plot(mu.use, type='l')
plot(sigma2.use, type='l')

#SUMMARIZE THE POSTERIOR DISTRIBUTION(S)
# posterior distribution of mu 
#plot 
plot(density(mu.use), xlab=expression(mu[D]), ylab="density", main=expression(pi(mu[D]~"|"~data)))
# #add prior
# curve(dnorm(x, lambda, sqrt(tau2)), lty=2, add=T)
#add legend
# legend("topright", c("Posterior"))
mean(mu.use)

muD.use <- mu.use

# posterior distribution of sigma2
par(mfrow=c(1,1))
plot(density(sigma2.use), xlab=expression(sigma[D]^2), main=expression(pi(sigma[D]^2~"|"~data)))
# #add prior
# curve(dinvgamma(x, gamma, phi), add=T, lty=2, xlim=c(0, 1))
#add legend
# legend("topright", c("Posterior"))
mean(sigma2.use)

sigma2D.use <- sigma2.use

```

```{r}

### Difference in means for Disney and LucasFilms

#Compare mu.D to mu.L
mean(muD.use > muL.use)
#Given our data and prior knowledge, there is about a 30% chance that 
#NYTimes Bestseller fiction books have a higher goodreads rating than nonfiction books

# Credible interval
diff <- muD.use - muL.use
plot(density(diff), xlab=expression(mu[D]-mu[L]), main="Posterior of Average Rating Disney vs LucasFilm")
abline(v=0, lty=2)

quantile(diff, c(.025, .975))


```



